version: '3.8'

services:
  app:
    build: .
    container_name: whatthecv-api
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    environment:
      - DATABASE_URL=postgres://${SUPABASE_USER}:${SUPABASE_PASSWORD}@${SUPABASE_HOST}:${SUPABASE_PORT}/${SUPABASE_DB}
      
  nginx:
    image: nginx:alpine
    container_name: whatthecv-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/html
    depends_on:
      - app
    restart: always 