services:
  - type: web
    name: whatthecv-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py --no-reload
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: whatthecv-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
    healthCheckPath: /
    plan: free
    autoDeploy: true

databases:
  - name: whatthecv-db
    plan: free 