name: Keep Backend API Alive

on:
  schedule:
    # Run every 2 hours
    - cron: '0 */2 * * *'
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend API
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://whatthecv-backend.fly.dev/
      
      - name: Log timestamp
        run: |
          echo "API pinged at $(date)" 